# Generated by Django 5.0.10 on 2024-12-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='position',
            field=models.CharField(blank=True, choices=[('Thacsi', 'Thạc sĩ'), ('Tiensi', 'Tiến sĩ')], default='Thacsi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='specialization',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(blank=True, choices=[('08:00-08:45', '08:00 - 08:45'), ('09:00-09:45', '09:00 - 09:45'), ('10:00-10:45', '10:00 - 10:45'), ('11:00-11:45', '11:00 - 11:45'), ('13:00-13:45', '13:00 - 13:45'), ('14:00-14:45', '14:00 - 14:45'), ('15:00-15:45', '15:00 - 15:45'), ('16:00-16:45', '16:00 - 16:45'), ('17:00-17:45', '17:00 - 17:45'), ('18:00-18:45', '18:00 - 18:45')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
