# Generated by Django 5.0.10 on 2024-12-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='position',
            field=models.CharField(blank=True, choices=[('Thạc sĩ', 'Thạc sĩ'), ('Tiến sĩ', 'Tiến sĩ')], default='Thạc sĩ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
