# Generated by Django 5.0.10 on 2024-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_appointment_address_appointment_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Chờ', 'Chờ'), ('Xác nhận', 'Xác nhận'), ('Hoàn thành', 'Hoàn thành')], default='Chờ', max_length=20, null=True),
        ),
    ]
