# Generated by Django 5.0.10 on 2024-12-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_medicalrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/img/medical_records'),
        ),
    ]
