# Generated by Django 5.0.10 on 2024-12-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_serviceitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='website.category'),
        ),
    ]
