# Generated by Django 5.0.10 on 2025-01-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_clinic_phone_number_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
