# Generated by Django 5.0.10 on 2024-12-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_medicalrecord_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/img/result'),
        ),
    ]
