# Generated by Django 5.0.10 on 2025-01-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='status',
            field=models.CharField(blank=True, choices=[('Chờ', 'Chờ'), ('Xác nhận', 'Xác nhận')], default='Chờ', max_length=20, null=True),
        ),
    ]
