# Generated by Django 5.0.10 on 2025-01-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_clinic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='is_approved',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
